### ISSUE TITLE
Not getting anywhere near 60 fps

### ISSUE THREAD

**Issue by shaps80** [objcio/S01E216-quick-open-optimizing-performance-part-2#3]
Not sure if you're still looking at this repo. But on the off chance you are I pulled the demo project from the last episode and ran the project on Apple Silicon. Expecting to get at least the 60 fps you showed in the video. Unfortunately it lags massively where you can't really 'type' the word string without waiting for the letters to 'catchup'. I'm a little baffled. Do you think this is related to M1?

**Comment by chriseidhof** [comment]
Hi @shaps80 ! Hm, that's interesting. Are you running this in Release mode? I just fired it up on my MBA (M1) and ran it in Instruments. It looks to be a little faster than on my 15" MBP. Haven't tested in detail.

How are you running this?

**Comment by shaps80** [comment]
Ahh you're absolutely right! I completely forgot to change that. Yeah you're right, amazing performance yet again 👍 

Thanks for getting back to me and thanks for posting that series. Really interesting insights @chriseidhof!
